version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: form_quiz_app
    ports:
      - "4000:80"
    volumes:
      - /DATA/AppData/form:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=form_db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass

  db:
    image: mysql:8.3
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: form_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
